version: '3'
services:

  server:
    container_name: server
    image: server:latest
    environment:
      - SERVER_PORT=12350
      - LOG_LEVEL=info
      - RABBITMQ_USER=root
      - RABBITMQ_PASSWORD=seba1234
      - N_PRODUCERS=1  # socket receive
      - N_CONSUMERS=${N_WORKER_INITIAL_STATE}
      - N_WORKER_FILTER_STUDENTS=${N_WORKER_FILTER_STUDENTS}
      - N_WORKER_INITIAL_STATE=${N_WORKER_INITIAL_STATE}
      - N_WORKER_MAP=${N_WORKER_MAP}
    entrypoint: /tp2/target/release/server
    networks:
      - tp2_net

  client:
    container_name: client
    image: client:latest
    environment:
      - SERVER_PORT=12350
      - FILENAME_POSTS=posts_full.csv
      - FILENAME_COMMENTS=comments_full.csv
      - LOG_LEVEL=info
    entrypoint: /tp2/target/release/client
    volumes:
      - ./downloads:/tp2/downloads
      - ./posts.csv:/tp2/posts.csv
      - ./posts_full.csv:/tp2/posts_full.csv
      - ./comments.csv:/tp2/comments.csv
      - ./comments_full.csv:/tp2/comments_full.csv
    depends_on:
      - server
    networks:
      - tp2_net

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=seba1234
    depends_on:
      - server
    networks:
      - tp2_net
    ports:
     - 15672:15672

  worker_initial_state:
    image: worker_initial_state:latest
    deploy:
      mode: replicated
      replicas: ${N_WORKER_INITIAL_STATE}
    entrypoint: /tp2/target/release/worker_initial_state
    environment:
      - LOG_LEVEL=info
      - RABBITMQ_USER=root
      - RABBITMQ_PASSWORD=seba1234
      - N_PRODUCERS=1   # 1 server
      - N_CONSUMERS=${N_WORKER_MAP}
    depends_on:
      - server
    networks:
      - tp2_net

  worker_avg:
    container_name: worker_avg
    image: worker_avg:latest
    entrypoint: /tp2/target/release/worker_avg
    environment:
      - LOG_LEVEL=info
      - RABBITMQ_USER=root
      - RABBITMQ_PASSWORD=seba1234
      - N_PRODUCERS=${N_WORKER_INITIAL_STATE}
      - N_CONSUMERS=1
    depends_on:
      - server  
    networks:
      - tp2_net
  
  worker_map:
    image: worker_map:latest
    entrypoint: /tp2/target/release/worker_map
    deploy:
      mode: replicated
      replicas: ${N_WORKER_MAP}
    environment:
      - RABBITMQ_USER=root
      - RABBITMQ_PASSWORD=seba1234
      - LOG_LEVEL=info
      - N_PRODUCERS=${N_WORKER_INITIAL_STATE}
      - N_CONSUMERS=${N_WORKER_FILTER_STUDENTS},1 # 1 worker_group_by
    depends_on:
      - server
    networks:
      - tp2_net

  worker_filter_students:
    image: worker_filter_students:latest
    entrypoint: /tp2/target/release/worker_filter_students
    deploy:
      mode: replicated
      replicas: ${N_WORKER_FILTER_STUDENTS}
    environment:
      - RABBITMQ_USER=root
      - RABBITMQ_PASSWORD=seba1234
      - LOG_LEVEL=info
      - N_PRODUCERS=${N_WORKER_MAP}
      - N_CONSUMERS=1 # 1 worker_join
    depends_on:
      - server
    networks:
      - tp2_net
  
  worker_filter_score:
    image: worker_filter_score:latest
    entrypoint: /tp2/target/release/worker_filter_score
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - LOG_LEVEL=info
      - RABBITMQ_USER=root
      - RABBITMQ_PASSWORD=seba1234
      - N_PRODUCERS=${N_WORKER_INITIAL_STATE},1 # 1 worker_avg
      - N_CONSUMERS=1 # 1 worker_join
    depends_on:
      - server
    networks:
      - tp2_net

  worker_join:
    container_name: worker_join
    image: worker_join:latest
    entrypoint: /tp2/target/release/worker_join
    environment:
      - LOG_LEVEL=info
      - RABBITMQ_USER=root
      - RABBITMQ_PASSWORD=seba1234
      - N_PRODUCERS=1,${N_WORKER_FILTER_STUDENTS}
    depends_on:
      - server
    networks:
      - tp2_net

  worker_group_by:
    container_name: worker_group_by
    image: worker_group_by:latest
    entrypoint: /tp2/target/release/worker_group_by
    environment:
      - LOG_LEVEL=info
      - RABBITMQ_USER=root
      - RABBITMQ_PASSWORD=seba1234
      - N_PRODUCERS=${N_WORKER_INITIAL_STATE},${N_WORKER_MAP}
    depends_on:
      - server
    networks:
      - tp2_net

networks:
  tp2_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
