pub const AVG_TO_FILTER_SCORE: &str = "AVG_TO_FILTER_SCORE";
pub const QUEUE_COMMENTS_TO_FILTER_STUDENTS: &str = "QUEUE_COMMENTS_TO_FILTER_STUDENTS";
pub const QUEUE_COMMENTS_TO_GROUP_BY: &str = "QUEUE_COMMENTS_TO_GROUP_BY";
pub const QUEUE_COMMENTS_TO_JOIN: &str = "QUEUE_COMMENTS_TO_JOIN";
pub const QUEUE_COMMENTS_TO_MAP: &str = "QUEUE_COMMENTS_TO_MAP";
pub const QUEUE_INITIAL_STATE: &str = "QUEUE_INITIAL_STATE";
pub const QUEUE_POSTS_TO_AVG: &str = "QUEUE_POSTS_TO_AVG";
pub const QUEUE_POSTS_TO_FILTER_SCORE: &str = "QUEUE_POSTS_TO_FILTER_SCORE";
pub const QUEUE_POSTS_TO_GROUP_BY: &str = "QUEUE_POSTS_TO_GROUP_BY";
pub const QUEUE_POSTS_TO_JOIN: &str = "QUEUE_POSTS_TO_JOIN";
pub const QUEUE_TO_CLIENT: &str = "QUEUE_TO_CLIENT";

pub const QUEUES: [&'static str; 10] = [
    AVG_TO_FILTER_SCORE,
    QUEUE_COMMENTS_TO_FILTER_STUDENTS,
    QUEUE_COMMENTS_TO_GROUP_BY,
    QUEUE_COMMENTS_TO_JOIN,
    QUEUE_COMMENTS_TO_MAP,
    QUEUE_INITIAL_STATE,
    QUEUE_POSTS_TO_AVG,
    QUEUE_POSTS_TO_FILTER_SCORE,
    QUEUE_POSTS_TO_GROUP_BY,
    QUEUE_POSTS_TO_JOIN
];